name: 'Generate README'

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  generate-readme:
    name: 'Generate README'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run README Generator
      run: |
        chmod +x ./src/readme_generator.sh
        ./src/readme_generator.sh

    - name: Push it back to Main
      run: |
        git config --global user.name 'OLeonardoRodrigues'
        git config --global user.email 'oleonardorodrigues@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Generate README"
        git push
    
