name: 'Tests'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  formatting:
    name: 'Formatting Cases'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Go to Examples FMT Dir
      run: cd ./examples/fmt

    - name: Case - Flaws False
      run: |
        cd ./flaws_false
        ../../../src/commands/fmt.sh
        
    - name: Case - Flaws True
      run: |
        cd ../flaws_true
        ../../../src/commands/fmt.sh
