name: 'Tests'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

env:
  TF_LOG: TRACE

jobs:
  formatting:
    name: 'Formatting Cases'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Case - Flaws False
      run: |
        ../../../src/cat_all.sh ./examples/fmt/flaws_true
        cd ./examples/fmt/flaws_false
        chmod +x ../../../src/commands/fmt.sh
        ../../../src/commands/fmt.sh
        ../../../src/cat_all.sh ./examples/fmt/flaws_true

    - name: Case - Flaws True
      run: |
        ../../../src/cat_all.sh ./examples/fmt/flaws_true
        cd ./examples/fmt/flaws_true
        chmod +x ../../../src/commands/fmt.sh
        ../../../src/commands/fmt.sh
        ../../../src/cat_all.sh ./examples/fmt/flaws_true
