name: 'Tests'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  formatting:
    name: 'Formatting Tests'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Run Flaws False Case
      run: |
        cd ./examples/fmt/flaws_false
        ../../../src/commands/fmt.sh
        
    - name: Run Flaws True Case
      run: |
        cd ./examples/fmt/flaws_true
        ../../../src/commands/fmt.sh
      
